import "./globals.css";
import AdminLayout from "./admin/adminLayout";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <AdminLayout>
          {children}
          </AdminLayout>
      </body>
    </html>
  );
}


// app/layout.js (global layout handler)
// import { usePathname } from 'next/navigation';
// import AdminLayout from './admin-layout';
// import CustomerLayout from './customer-layout';

// const Layout = ({ children }) => {
//   const pathname = usePathname();

//   // Check if the current route is for the admin section
//   if (pathname.startsWith('/admin')) {
//     return <AdminLayout>{children}</AdminLayout>;
//   }

//   // Use the customer layout for other routes
//   return <CustomerLayout>{children}</CustomerLayout>;
// };

// export default Layout;
